### ISSUE TITLE
为什么普通用户也无法ssh登陆了?

### ISSUE THREAD

**Issue by lvshuai789** [pssss/Security-Baseline#2]
请问执行脚本以后,为什么root和普通用户密码都正确但是却无法登陆了,提示密码错误

**Comment by pssss** [comment]
检查了一下，系脚本第61行配置问题：
`sed -ri '1a auth       required     pam_tally2.so deny=$deny unlock_time=300 even_deny_root root_unlock_time=30' /etc/pam.d/sshd /etc/pam.d/login /etc/pam.d/system-auth /etc/pam.d/password-auth`
将单引号改为双引号后测试正常，脚本已更新。
登录错误日志为：
`pam_tally2(sshd:auth): bad number supplied: deny=$deny`
目前已无法登录的服务器在web console重启时进入single模式（Centos 6）或 rd.break （Centos 7 ），修改 `/etc/pam.d/sshd、/etc/pam.d/login、/etc/pam.d/system-auth、/etc/pam.d/password-auth`  deny配置，重启系统可恢复正常。
[Centos 6 进入single模式](https://jingyan.baidu.com/article/d45ad148a61dbd69552b8018.html)
[Centos 7 rd.break](https://blog.51cto.com/meiling/2096125)
